// DWEX Broker Phases Configuration
// Each broker phase defines a broker integration with its capabilities and status

export interface BrokerPhase {
  id: string
  name: string
  color: string
  assetCount: number
  status: 'active' | 'coming' | 'maintenance'
  description: string
  supportedCategories: string[]
  leverageMax: number
  minDeposit: number
  commission: number
  features: string[]
}

export const brokerPhases: BrokerPhase[] = [
  {
    id: 'deriv',
    name: 'Deriv',
    color: '#00A88A',
    assetCount: 200,
    status: 'active',
    description: 'Forex, Synthetics, Crypto',
    supportedCategories: ['forex', 'crypto', 'synthetics', 'commodities'],
    leverageMax: 1000,
    minDeposit: 5,
    commission: 0.0,
    features: ['synthetics', 'multiplier', 'digital-options'],
  },
  {
    id: 'wise',
    name: 'Wise',
    color: '#3B82F6',
    assetCount: 50,
    status: 'active',
    description: 'Fiat transfers, Multi-currency',
    supportedCategories: ['forex'],
    leverageMax: 1,
    minDeposit: 1,
    commission: 0.003,
    features: ['fiat-transfer', 'multi-currency', 'low-fees'],
  },
  {
    id: 'eversend',
    name: 'Eversend',
    color: '#E5940A',
    assetCount: 30,
    status: 'active',
    description: 'African currencies, Wallet',
    supportedCategories: ['forex'],
    leverageMax: 1,
    minDeposit: 1,
    commission: 0.005,
    features: ['african-currencies', 'wallet', 'bill-payments'],
  },
  {
    id: 'binance',
    name: 'Binance',
    color: '#B8860B',
    assetCount: 350,
    status: 'active',
    description: 'Crypto exchange, Futures',
    supportedCategories: ['crypto'],
    leverageMax: 125,
    minDeposit: 1,
    commission: 0.001,
    features: ['futures', 'spot', 'p2p', 'earn'],
  },
  {
    id: 'exness',
    name: 'Exness',
    color: '#8B5CF6',
    assetCount: 120,
    status: 'active',
    description: 'Forex, Commodities, Indices',
    supportedCategories: ['forex', 'commodities', 'indices'],
    leverageMax: 2000,
    minDeposit: 1,
    commission: 0.0,
    features: ['unlimited-leverage', 'instant-withdrawal', 'zero-spread'],
  },
  {
    id: 'xm',
    name: 'XM',
    color: '#EC4899',
    assetCount: 100,
    status: 'coming',
    description: 'Forex, Stocks, Indices',
    supportedCategories: ['forex', 'stocks', 'indices'],
    leverageMax: 888,
    minDeposit: 5,
    commission: 0.0,
    features: ['micro-lots', 'no-requotes', 'free-education'],
  },
  {
    id: 'fbs',
    name: 'FBS',
    color: '#EF4444',
    assetCount: 80,
    status: 'coming',
    description: 'Forex, Commodities',
    supportedCategories: ['forex', 'commodities'],
    leverageMax: 3000,
    minDeposit: 1,
    commission: 0.0,
    features: ['swap-free', 'cashback', 'level-up'],
  },
  {
    id: 'octafx',
    name: 'OctaFX',
    color: '#F97316',
    assetCount: 60,
    status: 'coming',
    description: 'Forex, Indices',
    supportedCategories: ['forex', 'indices'],
    leverageMax: 500,
    minDeposit: 20,
    commission: 0.0,
    features: ['copy-trading', 'swap-free', 'contest'],
  },
  {
    id: 'icmarkets',
    name: 'IC Markets',
    color: '#06B6D4',
    assetCount: 90,
    status: 'coming',
    description: 'Forex, CFDs',
    supportedCategories: ['forex', 'commodities', 'indices'],
    leverageMax: 500,
    minDeposit: 200,
    commission: 0.0035,
    features: ['raw-spread', 'ecn', 'fast-execution'],
  },
  {
    id: 'hfm',
    name: 'HFM',
    color: '#14B8A6',
    assetCount: 70,
    status: 'coming',
    description: 'Forex, Stocks',
    supportedCategories: ['forex', 'stocks'],
    leverageMax: 1000,
    minDeposit: 5,
    commission: 0.0,
    features: ['zero-spread', 'copy-trading', 'bonus'],
  },
  {
    id: 'chipper',
    name: 'Chipper Cash',
    color: '#84CC16',
    assetCount: 25,
    status: 'coming',
    description: 'African currencies, Crypto',
    supportedCategories: ['forex', 'crypto'],
    leverageMax: 1,
    minDeposit: 1,
    commission: 0.0,
    features: ['p2p', 'no-fees', 'african-focus'],
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    color: '#22C55E',
    assetCount: 40,
    status: 'coming',
    description: 'US Stocks, ETFs',
    supportedCategories: ['stocks', 'etfs'],
    leverageMax: 1,
    minDeposit: 10,
    commission: 0.009,
    features: ['fractional-shares', 'us-stocks', 'auto-invest'],
  },
  {
    id: 'chaka',
    name: 'Chaka',
    color: '#A855F7',
    assetCount: 35,
    status: 'coming',
    description: 'Nigerian & US Stocks',
    supportedCategories: ['stocks'],
    leverageMax: 1,
    minDeposit: 10,
    commission: 0.01,
    features: ['nigerian-stocks', 'us-stocks', 'dual-market'],
  },
  {
    id: 'risevest',
    name: 'Risevest',
    color: '#F43F5E',
    assetCount: 30,
    status: 'coming',
    description: 'US Stocks, ETFs',
    supportedCategories: ['stocks', 'etfs'],
    leverageMax: 1,
    minDeposit: 10,
    commission: 0.01,
    features: ['auto-invest', 'managed-portfolio', 'us-stocks'],
  },
  {
    id: 'revolut',
    name: 'Revolut',
    color: '#6366F1',
    assetCount: 60,
    status: 'coming',
    description: 'Forex, Stocks, Crypto',
    supportedCategories: ['forex', 'stocks', 'crypto'],
    leverageMax: 30,
    minDeposit: 0,
    commission: 0.0,
    features: ['multi-currency', 'spare-change', 'crypto'],
  },
  {
    id: 'bybit',
    name: 'Bybit',
    color: '#F59E0B',
    assetCount: 200,
    status: 'coming',
    description: 'Crypto, Futures',
    supportedCategories: ['crypto'],
    leverageMax: 100,
    minDeposit: 1,
    commission: 0.001,
    features: ['futures', 'spot', 'copy-trading', 'earn'],
  },
  {
    id: 'kucoin',
    name: 'KuCoin',
    color: '#10B981',
    assetCount: 180,
    status: 'coming',
    description: 'Altcoins, Crypto',
    supportedCategories: ['crypto'],
    leverageMax: 100,
    minDeposit: 0,
    commission: 0.001,
    features: ['altcoins', 'futures', 'trading-bot', 'earn'],
  },
  {
    id: 'okx',
    name: 'OKX',
    color: '#8B5CF6',
    assetCount: 150,
    status: 'coming',
    description: 'Crypto, Commodities',
    supportedCategories: ['crypto', 'commodities'],
    leverageMax: 125,
    minDeposit: 1,
    commission: 0.0008,
    features: ['futures', 'options', 'defi', 'copy-trading'],
  },
]

export function getBrokerById(brokerId: string): BrokerPhase | undefined {
  return brokerPhases.find(b => b.id === brokerId)
}

export function getActiveBrokers(): BrokerPhase[] {
  return brokerPhases.filter(b => b.status === 'active')
}

export function isBrokerActive(brokerId: string): boolean {
  const broker = getBrokerById(brokerId)
  return broker?.status === 'active'
}
